source/myapp/src/Entity/Commit.php
<?php

namespace App\Entity;

use App\Repository\CommitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=CommitRepository::class)
 * @ORM\Table(name="`commit`")
 * @UniqueEntity(fields="sha", message="Commit is already stored!")
 */
class Commit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $sha;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author_email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSha(): ?string
    {
        return $this->sha;
    }

    public function setSha(string $sha): self
    {
        $this->sha = $sha;

        return $this;
    }

    public function getAuthorName(): ?string
    {
        return $this->author_name;
    }

    public function setAuthorName(string $author_name): self
    {
        $this->author_name = $author_name;

        return $this;
    }

    public function getAuthorEmail(): ?string
    {
        return $this->author_email;
    }

    public function setAuthorEmail(string $author_email): self
    {
        $this->author_email = $author_email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

source/myapp/src/Controller/CommitController.php
<?php

namespace App\Controller;

use App\Repository\CommitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\HttpClientClass;
class CommitController extends AbstractController
{
    /**
     * @Route("/commits", name="commit")
     */
    public function index(CommitRepository $commitRepository): Response
    {
        return $this->render('commit/index.html.twig', [
            'controller_name' => 'CommitController',
            'commits' => $commitRepository->findAll()
        ]);
    }

}

source/myapp/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

source/myapp/templates/commit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CommitController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    tr.active { color: #E6F1F6 }
</style>

<div class="example-wrapper">
    <h1>Last commits by  {{ controller_name }}! ✅</h1>

    Commit List:
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Author name</th>
                <th>Author email</th>
                <th>SHA</th>
            </tr>
        </thead>
        <tbody>
            {% for commit in commits %}
            <tr {% if endsInNumber(commit.sha) %} class="active" {% endif %}>
                <td>{{loop.index}}</td>
                <td>{{commit.authorName}}</td>
                <td>{{commit.authorEmail}}</td>
                <td>{{commit.sha}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}